const STUDY_COURSES = [
  {
    id: "redes",
    name: "Redes de Computadores",
    icon: "-",
    chapters: [
      {
        id: "redes-1",
        name: "Cap 1 — Evolução das Redes",
        cards: [
          { q: "A ARPANET foi projetada para ser descentralizada. Por que essa decisão arquitetural era crítica no contexto militar dos anos 1960?", a: "Para sobreviver a ataques nucleares — se um nó fosse destruído, os pacotes seriam roteados por caminhos alternativos. Redes centralizadas teriam ponto único de falha." },
          { q: "Um administrador configura um servidor DHCP na rede. Esse serviço é classificado como de Aplicação, Operacional ou Administrativo? Justifique.", a: "Operacional — DHCP é um serviço de suporte à rede (atribui IPs automaticamente), não é usado diretamente pelo usuário final (Aplicação) nem para gerenciar/monitorar a rede (Administrativo)." },
          { q: "Uma empresa tem filiais em São Paulo, Rio e BH conectadas por links dedicados. Essa rede é classificada como LAN, MAN ou WAN? E se todas ficassem dentro da mesma cidade?", a: "Interestadual = WAN (abrange grande distância). Se fossem na mesma cidade = MAN (rede metropolitana). LAN seria apenas dentro de um prédio/campus." },
          { q: "No FTP, por que são usadas DUAS portas (20 e 21) em vez de uma só como HTTP (80)?", a: "Porta 21 = canal de controle (comandos/autenticação, permanece aberta). Porta 20 = canal de dados (transferência de arquivos, aberta sob demanda). Separar permite controlar a transferência sem interromper a sessão de comando." },
          { q: "Um ISP oferece FTTH e outro oferece conexão via satélite GEO. Para uma aplicação de videoconferência em tempo real, qual é melhor e por quê?", a: "FTTH — latência muito menor (~1-5 ms) vs GEO (~600 ms ida+volta devido à distância de ~35.786 km). Videoconferência é sensível a latência; GEO causaria atrasos perceptíveis." },
          { q: "Em uma rede peer-to-peer, um vírus infecta um nó. Por que a propagação é potencialmente mais rápida do que em cliente-servidor?", a: "Em P2P cada nó se comunica diretamente com vários outros (sem intermediário central), então o vírus pode se propagar exponencialmente. Em cliente-servidor, a comunicação é mediada — o servidor pode filtrar/bloquear." },
          { q: "SDN separa o plano de controle do plano de dados. Se o controlador centralizado ficar offline, o que acontece com o encaminhamento de pacotes nos switches?", a: "Os switches mantêm as regras já instaladas nas tabelas de fluxo (plano de dados continua). Porém, novos fluxos não são tratados e alterações dinâmicas param — o controlador é um ponto único de falha lógico." },
          { q: "Uma PAN Bluetooth conecta fone, relógio e celular. Se o usuário adicionar um notebook via Wi-Fi Direct ao celular, isso ainda é uma PAN?", a: "Sim — PAN é definida pelo alcance pessoal (~metros ao redor do usuário), não pela tecnologia. Bluetooth e Wi-Fi Direct coexistem numa PAN." },
          { q: "A Starlink usa satélites LEO em vez de GEO. Cite uma desvantagem de LEO que GEO não tem.", a: "LEO precisa de constelações de centenas/milhares de satélites porque cada um cobre uma área pequena e se move rápido. GEO fica fixo sobre um ponto — 3 satélites cobrem quase toda a Terra." },
        ]
      },
      {
        id: "redes-2",
        name: "Cap 2 — Topologias e TCP/IP",
        cards: [
          { q: "Uma rede com 10 computadores em topologia mesh completa precisa de quantas conexões? E se migrar para estrela?", a: "Mesh: N×(N-1)/2 = 10×9/2 = 45 conexões. Estrela: apenas 10 (uma por dispositivo ao switch central). Mesh tem redundância total mas custo 4,5x maior." },
          { q: "Um streaming de vídeo ao vivo usa UDP em vez de TCP. Se pacotes se perdem, o vídeo trava ou continua? Explique a decisão de design.", a: "Continua (com possíveis artefatos visuais). UDP não retransmite pacotes perdidos — em streaming ao vivo, receber um frame atrasado é pior que pular um frame. TCP retransmitiria, causando atrasos cumulativos." },
          { q: "Na topologia em anel, se um computador for desconectado, a rede inteira cai. Como o anel duplo resolve isso?", a: "Anel duplo tem dois anéis em sentidos opostos. Se um nó/link falha, o tráfego é redirecionado pelo anel secundário, formando um loop que bypassa a falha — tolerância a 1 falha." },
          { q: "Um desenvolvedor precisa transmitir dados confiáveis por múltiplos caminhos simultâneos (multihoming). TCP ou SCTP? Por quê?", a: "SCTP — suporta multihoming nativo (múltiplos IPs por endpoint) e multi-streaming. TCP é single-homed e sofre de head-of-line blocking. SCTP foi projetado exatamente para esse caso (telefonia SS7 sobre IP)." },
          { q: "Você faz 'ping 8.8.8.8' e recebe 'TTL expired in transit'. O que isso indica sobre a rede?", a: "O pacote ICMP passou por tantos roteadores que o TTL chegou a zero antes de alcançar o destino. Indica: possível loop de roteamento, ou destino muito distante, ou TTL inicial configurado muito baixo." },
          { q: "Numa topologia em árvore, a falha de um switch intermediário isola toda a sub-árvore abaixo dele. Que topologia combinaria com árvore para resolver isso?", a: "Adicionar links mesh entre switches intermediários (topologia híbrida árvore+mesh), criando caminhos redundantes. É o que redes reais fazem no modelo hierárquico (Core/Distribution/Access) com links redundantes entre camadas." },
          { q: "A camada de Transporte do TCP/IP é responsável pela entrega fim-a-fim. Se um pacote chega corrompido, quem detecta: a camada de Transporte ou de Rede?", a: "Transporte (TCP) — usa checksum para detectar corrupção e solicita retransmissão. A camada de Rede (IP) também tem checksum mas apenas do cabeçalho, não dos dados. Se usar UDP, a detecção é opcional e não há retransmissão." },
          { q: "Qual a diferença prática entre a camada de 'Acesso à Rede' do TCP/IP e as camadas 'Física + Enlace' do modelo OSI?", a: "Funcionalmente são equivalentes — TCP/IP juntou em uma só por pragmatismo (não especifica detalhes dessas camadas). OSI separou para padronizar: Física = bits no meio, Enlace = frames com MAC address e detecção de erros." },
        ]
      },
      {
        id: "redes-3",
        name: "Cap 3 — Meios de Transmissão",
        cards: [
          { q: "Um data center tem interferência eletromagnética forte de geradores. Cabo UTP, F-UTP ou S-FTP? Justifique.", a: "S-FTP — tem blindagem dupla (folha geral + blindagem individual por par trançado), oferecendo máxima proteção contra EMI. UTP não tem blindagem nenhuma; F-UTP só tem folha geral, insuficiente para ambiente severo." },
          { q: "Um projeto exige 10 Gbps em lances de 55 metros. CAT6 atende? E CAT6a? Qual a diferença crítica?", a: "CAT6 suporta 10 Gbps apenas até 55 metros (limite exato do cenário — risco no limite). CAT6a suporta 10 Gbps até 100 metros. Diferença: CAT6a opera a 500 MHz vs 250 MHz do CAT6, com melhor alien crosstalk." },
          { q: "Uma empresa precisa conectar dois prédios a 5 km de distância. Fibra monomodo ou multimodo? E se fossem 200 metros?", a: "5 km = monomodo (alcance até ~100 km, um raio de luz). 200 m = multimodo bastaria (alcance até ~2 km, mais barata, conectores mais fáceis). Monomodo em 200 m funciona mas é desperdício de custo." },
          { q: "Por que fibra óptica é imune a interferência eletromagnética mas cabo de cobre não?", a: "Fibra transmite luz (fótons) através de vidro/plástico — campos eletromagnéticos não afetam fótons. Cobre transmite sinais elétricos (elétrons) — campos EM induzem correntes parasitas que distorcem o sinal." },
          { q: "Cabo coaxial de 75 ohm é usado para TV a cabo, mas por que NÃO é ideal para redes Ethernet?", a: "75 ohm é otimizado para menor atenuação de sinal (ideal para vídeo em longas distâncias). 50 ohm é otimizado para máxima transferência de potência (ideal para dados digitais). Impedância errada causa reflexões e perda de pacotes." },
          { q: "Uma operadora anuncia 'internet via satélite com baixa latência'. Isso é mais provável GEO ou LEO? Qual a latência típica de cada?", a: "LEO — latência ~20-40 ms (órbita 160-2000 km). GEO tem latência ~600 ms ida+volta (órbita ~35.786 km). 'Baixa latência via satélite' indica LEO (ex: Starlink)." },
          { q: "Em que situação usar Wi-Fi (ondas eletromagnéticas) é melhor que cabo Ethernet, mesmo com menor velocidade e confiabilidade?", a: "Mobilidade (dispositivos que se movem — celulares, notebooks em reuniões), locais onde cabeamento é inviável (prédios históricos, áreas externas), redes temporárias (eventos), ou custo de instalação proibitivo." },
          { q: "CAT7 suporta 10 Gbps a 600 MHz. Por que não é amplamente adotado em vez de CAT6a?", a: "CAT7 usa conectores proprietários (GG45/TERA, não RJ-45 padrão), é mais caro e mais rígido. CAT6a atinge 10 Gbps com conectores RJ-45 padrão. Na prática, quando se precisa de mais que 10 Gbps, migra-se para fibra." },
        ]
      },
      {
        id: "redes-4",
        name: "Cap 4 — Protocolos e Padrões",
        cards: [
          { q: "Um protocolo define 'Linguagem' como um de seus 6 elementos. HTTP usa texto legível (GET /index.html). Cite um protocolo que usa linguagem binária e por quê.", a: "HTTP/2 — usa frames binários em vez de texto para eficiência (menor overhead de parsing, multiplexação). Outros exemplos: DNS (formato binário compacto), protocolos de streaming (RTP)." },
          { q: "IEEE define 802.3 (Ethernet) e 802.11 (Wi-Fi). Por que são padrões separados se ambos operam nas mesmas camadas (Física + Enlace)?", a: "Meios de transmissão completamente diferentes: 802.3 usa cabo (transmissão determinística, CSMA/CD), 802.11 usa rádio (compartilhamento do espectro, CSMA/CA, problemas de hidden node). Precisam de MACs e PHYs distintos." },
          { q: "Durante o encapsulamento, dados viram Segmento na camada de Transporte. Se o protocolo for UDP (sem conexão), ainda chamamos de 'segmento'?", a: "Não — com UDP chamamos de 'datagrama'. 'Segmento' é específico do TCP (que segmenta dados em pedaços ordenados). A terminologia correta é: TCP=segmento, UDP=datagrama, IP=pacote, Enlace=frame." },
          { q: "O IETF publica padrões como RFCs, enquanto a IEEE publica padrões 802.x. Qual organização padronizou o TCP/IP e qual padronizou o Ethernet?", a: "TCP/IP = IETF (RFC 793 para TCP, RFC 791 para IP). Ethernet = IEEE (802.3). O IETF foca em protocolos de Internet (camadas 3+), IEEE foca em padrões de rede local (camadas 1-2)." },
          { q: "SNMP opera na camada de Aplicação mas gerencia dispositivos de todas as camadas. Como ele consegue monitorar um switch (camada 2)?", a: "SNMP usa agentes instalados nos dispositivos que expõem informações via MIBs (Management Information Base). O switch tem um agente SNMP que reporta dados de camada 2 (portas, MACs, erros) através de mensagens de camada 7." },
          { q: "No desencapsulamento, um roteador remove o header de Enlace e adiciona um novo. Por que o header de Enlace muda a cada salto mas o de Rede (IP) permanece?", a: "O header de Enlace contém MACs de origem/destino do próximo salto (muda em cada link). O header IP contém IPs de origem/destino final (fim-a-fim, não muda). Roteador opera na camada 3 — reescreve L2 para o próximo hop." },
          { q: "A ISO criou o modelo OSI com 7 camadas, mas o TCP/IP de 4 camadas 'venceu' na prática. Por que o mercado preferiu TCP/IP?", a: "TCP/IP já estava implementado e funcionando (pragmatismo > teoria). OSI era complexo, com camadas redundantes (Sessão/Apresentação raramente implementadas separadamente). TCP/IP tinha adoção massiva via ARPANET/Internet antes do OSI ser finalizado." },
          { q: "O W3C padroniza HTML/CSS/HTTP enquanto o IETF padroniza TCP/IP. Se surgir um novo protocolo de transporte para a web, quem o padronizaria?", a: "IETF — protocolos de transporte são seu domínio (ex: QUIC foi padronizado pelo IETF como RFC 9000, mesmo sendo criado pelo Google para a web). W3C padroniza tecnologias de conteúdo web, não de transporte." },
        ]
      },
      {
        id: "redes-5",
        name: "Cap 5 — IPv4, IPv6 e Endereçamento",
        cards: [
          { q: "Uma empresa recebeu o bloco 192.168.10.0/24 e precisa criar 4 sub-redes iguais. Qual máscara usar e quantos hosts por sub-rede?", a: "/26 (255.255.255.192). 4 sub-redes = 2 bits emprestados. Cada sub-rede: 2^6 - 2 = 62 hosts. Sub-redes: .0/26, .64/26, .128/26, .192/26." },
          { q: "O endereço 172.20.5.100 é público ou privado? Como saber sem decorar faixas?", a: "Privado — está na faixa 172.16.0.0 a 172.31.255.255 (Classe B privada, RFC 1918). As 3 faixas privadas: 10.0.0.0/8, 172.16.0.0/12, 192.168.0.0/16." },
          { q: "IPv6 removeu o campo Checksum do cabeçalho. Isso não torna o IPv6 menos confiável que IPv4?", a: "Não — o checksum IP era redundante porque TCP/UDP já fazem verificação de integridade, e Ethernet (L2) também verifica CRC. Removê-lo reduz processamento em cada roteador (IPv4 recalculava checksum a cada hop por causa do TTL)." },
          { q: "Um roteador recebe um pacote IPv4 com TTL=1. O que ele faz?", a: "Descarta o pacote e envia uma mensagem ICMP Time Exceeded (tipo 11) ao remetente. Não encaminha porque decrementar TTL resultaria em 0. É assim que o traceroute funciona — envia pacotes com TTL incremental." },
          { q: "O endereço IPv6 2001:0db8:0000:0000:0000:0000:0000:0001 pode ser abreviado de duas formas. Quais?", a: "2001:db8::1 (omitir zeros à esquerda + :: para grupos contíguos de zeros). A regra: :: só pode aparecer UMA vez. Outra forma intermediária: 2001:db8:0:0:0:0:0:1 (sem ::, zeros à esquerda omitidos)." },
          { q: "Uma rede usa dual-stack (pilha dupla) para transição IPv4→IPv6. Qual o principal problema operacional dessa abordagem?", a: "Manter e gerenciar DOIS protocolos simultaneamente — dobra a complexidade: duas tabelas de roteamento, dois conjuntos de firewall rules, dois planos de endereçamento, dois conjuntos de monitoramento. Custo operacional alto." },
          { q: "O endereço 127.0.0.1 é de qual classe? É roteável? Por que toda a faixa 127.0.0.0/8 foi reservada para loopback?", a: "Classe A (primeiro octeto 1-126, mas 127 é exceção reservada). NÃO é roteável — pacotes para 127.x.x.x nunca saem da máquina. Toda a /8 foi reservada por design original, embora na prática só 127.0.0.1 seja usado." },
          { q: "NAT64 traduz IPv6 para IPv4. Em que cenário isso é necessário em vez de dual-stack ou túnel?", a: "Quando uma rede é IPv6-only (sem IPv4) mas precisa acessar servidores que só têm IPv4. DNS64 sintetiza um endereço IPv6 falso, e o NAT64 traduz os pacotes na borda. Usado em operadoras móveis para economizar endereços IPv4." },
          { q: "Quantos endereços de host são possíveis em uma rede /20? Mostre o cálculo.", a: "32 - 20 = 12 bits para hosts. 2^12 = 4096 endereços totais. 4096 - 2 = 4094 hosts utilizáveis (subtrai endereço de rede e broadcast)." },
          { q: "O campo IHL do cabeçalho IPv4 indica o tamanho do cabeçalho em palavras de 32 bits. Se IHL=5, qual o tamanho em bytes? E se IHL=15?", a: "IHL=5: 5×4 = 20 bytes (cabeçalho mínimo, sem opções). IHL=15: 15×4 = 60 bytes (cabeçalho máximo, com 40 bytes de opções). IHL mínimo é sempre 5." },
        ]
      },
      {
        id: "redes-6",
        name: "Cap 6 — Protocolos de Aplicação",
        cards: [
          { q: "Um admin usa Telnet para configurar um switch. Um atacante na mesma rede captura as credenciais. Por que isso é possível com Telnet mas não com SSH?", a: "Telnet transmite TUDO em texto puro (RFC 854), incluindo usuário e senha. SSH (RFC 4254) criptografa toda a sessão desde o handshake. Na mesma rede, um sniffer captura facilmente Telnet mas vê apenas dados cifrados com SSH." },
          { q: "Um e-mail é enviado de Gmail para Outlook. Quais protocolos são usados em cada etapa: envio, transporte entre servidores e leitura?", a: "Envio: SMTP (cliente→servidor Gmail). Transporte: SMTP (servidor Gmail→servidor Outlook, via MTA relay). Leitura: IMAP4 ou POP3 (cliente Outlook baixa do servidor). SMTP só envia, nunca baixa." },
          { q: "Um funcionário usa POP3 no notebook do trabalho. Ao chegar em casa, abre o webmail e não encontra os e-mails. Por quê? Qual protocolo resolveria?", a: "POP3 baixa e-mails e os REMOVE do servidor por padrão. IMAP4 resolveria — mantém os e-mails no servidor e sincroniza entre todos os dispositivos." },
          { q: "A resolução DNS começa no resolver recursivo. Se o resolver já tem 'google.com' em cache, ele ainda consulta o Root NS?", a: "Não — o cache evita consultas desnecessárias. O resolver retorna direto o IP cacheado enquanto o TTL não expirar. É por isso que a primeira consulta DNS é mais lenta que as subsequentes." },
          { q: "DNS usa UDP na porta 53 normalmente. Cite dois cenários em que DNS obrigatoriamente usa TCP.", a: "1) Resposta > 512 bytes (o servidor sinaliza 'truncated' e o cliente refaz via TCP). 2) Transferência de zona/AXFR (replicação completa entre servidores DNS autoritativos). DNSSEC também pode forçar TCP por respostas grandes." },
          { q: "FTP no modo ativo falha quando o cliente está atrás de NAT/firewall. Por que o modo passivo resolve isso?", a: "Modo ativo: o SERVIDOR inicia conexão de dados para o IP:porta do cliente — o NAT/firewall bloqueia conexões de entrada não solicitadas. Modo passivo: o CLIENTE inicia ambas as conexões (controle + dados) — só conexões de saída, que NAT permite." },
          { q: "HTTP/1.0 abre uma conexão TCP nova para cada recurso. Uma página com 20 imagens gera quantas conexões? Como HTTP/1.1 melhora isso?", a: "HTTP/1.0: 21 conexões TCP (1 para HTML + 20 para imagens), cada uma com overhead de handshake 3-way. HTTP/1.1: conexão persistente — reutiliza a mesma conexão TCP para múltiplas requisições sequenciais, reduzindo drasticamente a latência." },
          { q: "Um site roda na porta 8080 em vez da 80. O navegador precisa de algo especial na URL? Por quê?", a: "Sim — http://site.com:8080. Portas padrão (80 para HTTP, 443 para HTTPS) são implícitas e omitidas na URL. Qualquer outra porta precisa ser especificada explicitamente porque o navegador tentaria a porta padrão." },
        ]
      },
      {
        id: "redes-7",
        name: "Cap 7 — TCP/IP Avançado e Wireless",
        cards: [
          { q: "TCP/IP não tem segurança nativa. IPSec foi criado para resolver isso. Em qual camada do TCP/IP o IPSec opera e por quê?", a: "Camada de Internet (Rede) — opera no nível IP para proteger TODO o tráfego acima (TCP, UDP, SCTP), de forma transparente para as aplicações. Se fosse na camada de Transporte ou Aplicação, cada protocolo/app precisaria implementar sua própria segurança." },
          { q: "O modelo OSI tem 7 camadas e o TCP/IP tem 4. Um professor pergunta: 'onde fica a criptografia SSL/TLS no modelo OSI?'. Responda e justifique.", a: "Entre Transporte (L4) e Aplicação (L7) — mais precisamente na camada de Apresentação (L6), que é responsável por formatação, criptografia e compressão. No TCP/IP, isso fica dentro da camada de Aplicação (que absorveu Sessão+Apresentação)." },
          { q: "Uma piconet Bluetooth tem 1 mestre e 7 escravos ativos. Se um 8º dispositivo quiser se conectar, o que acontece?", a: "Ele entra no estado 'estacionado' (parked) — pode haver até 255 dispositivos estacionados. Estacionados estão sincronizados mas não podem transmitir dados. O mestre precisa 'desestacionar' um para ele se tornar ativo (max 7 ativos)." },
          { q: "5G promete latência < 1 ms. Para que tipo de aplicação essa latência ultra-baixa é essencial e por que 4G (~50 ms) não serve?", a: "Cirurgias remotas, veículos autônomos e automação industrial em tempo real. A 50 ms, um carro a 100 km/h percorre ~1,4 m antes de reagir — inaceitável para frenagem de emergência. A < 1 ms, percorre ~0,03 m." },
          { q: "6LoWPAN adapta IPv6 para IoT. O principal problema do IPv6 em dispositivos IoT é o tamanho do cabeçalho (40 bytes). Como 6LoWPAN resolve?", a: "Compressão de cabeçalho — reduz os 40 bytes do IPv6 para ~2-7 bytes usando contexto compartilhado (endereços deriváveis do link-local, campos inferidos). Também fragmenta pacotes IPv6 grandes para caber em frames IEEE 802.15.4 (127 bytes max)." },
          { q: "Uma scatternet conecta duas piconets via um dispositivo que participa de ambas. Esse dispositivo pode ser mestre nas duas piconets?", a: "Não — um dispositivo pode ser mestre em apenas uma piconet. Na outra, ele deve ser escravo. Isso porque o mestre define o clock e o padrão de saltos de frequência — dois masteres no mesmo dispositivo causariam conflito." },
          { q: "Cite uma estratégia de inovação TCP/IP que FUNDE duas camadas e uma que DIVIDE. Dê exemplos concretos.", a: "Fusão: IPSec funde segurança na camada de Rede (antes separada). Divisão: 6LoWPAN divide a camada de Adaptação em sub-camadas para compressão e fragmentação entre IPv6 e IEEE 802.15.4." },
          { q: "TCP/IP tem o problema de 'independência excessiva entre camadas'. Em que cenário prático isso causa ineficiência?", a: "TCP retransmite pacotes perdidos sem saber que a perda foi por mobilidade (handoff Wi-Fi), não por congestionamento. A camada de Transporte assume congestionamento e reduz a velocidade desnecessariamente. Se as camadas se comunicassem, TCP saberia que é handoff e manteria a taxa." },
        ]
      },
      {
        id: "redes-8",
        name: "Cap 8 — Projeto de Rede",
        cards: [
          { q: "No modelo hierárquico de 3 camadas, um switch de acesso falha. O impacto é local ou afeta toda a rede? E se falhar um switch de núcleo?", a: "Acesso: impacto local — apenas os dispositivos conectados àquele switch ficam offline. Núcleo: impacto global — o backbone de alta velocidade cai, isolando segmentos inteiros da rede. Por isso, o núcleo deve ter redundância." },
          { q: "O 'netstat -an' mostra a porta 4444 em estado LISTENING. O admin não reconhece esse serviço. Que risco isso indica e qual o próximo passo?", a: "Porta 4444 é comumente usada por backdoors/trojans (ex: Metasploit default). Risco: possível comprometimento. Próximo passo: identificar o processo (netstat -anp no Linux / netstat -ano no Windows para ver o PID), investigar o executável, verificar com antimalware." },
          { q: "O comando 'ping 10.0.0.1' retorna 'Destination Host Unreachable' em vez de 'Request Timed Out'. Qual a diferença entre essas mensagens?", a: "Host Unreachable: o roteador mais próximo sabe que o host existe na sub-rede mas NÃO responde (pode estar offline). Request Timed Out: nenhuma resposta voltou — pode ser firewall bloqueando ICMP, rota inexistente, ou host realmente inalcançável." },
          { q: "Uma documentação AS BUILT difere do projeto original. O switch 3 foi movido do rack A para o rack B. Por que atualizar o AS BUILT é crítico?", a: "Sem AS BUILT atualizado, troubleshooting físico consulta documentação errada — o técnico vai ao rack A e não encontra o switch. Em incidentes urgentes, isso gera atraso. AS BUILT é a 'verdade' da rede, não o projeto original." },
          { q: "Um roteador doméstico tem 'Block ICMP Ping' ativado. Qual o trade-off de segurança vs operação?", a: "Segurança: impede atacantes de descobrir que o host existe (reconhecimento). Operação: impossibilita diagnóstico com ping/traceroute — dificulta troubleshooting legítimo. Em redes corporativas, geralmente permite ICMP interno e bloqueia externo." },
          { q: "O coworking do exemplo do PDF tem 73 m² e 66 pontos de rede. Isso é ~1 ponto por m². Em um escritório normal, qual seria a proporção típica?", a: "Coworking tem densidade alta porque cada estação precisa de tomada de rede. Escritório típico: ~1 ponto por 4-6 m² (considera salas de reunião, corredores, áreas sem uso de rede). A densidade do coworking é 4-6x maior que o normal." },
          { q: "O comando 'ipconfig /all' mostra DHCP Enabled: Yes mas o IP começa com 169.254.x.x. O que isso significa?", a: "APIPA (Automatic Private IP Addressing) — o cliente DHCP não conseguiu contatar um servidor DHCP e auto-atribuiu um IP link-local 169.254.0.0/16. A máquina NÃO tem conectividade real. Causa: DHCP server offline, cabo desconectado, ou problema de VLAN." },
          { q: "No projeto lógico de rede, por que separar tráfego de VoIP e dados em VLANs diferentes?", a: "VoIP é sensível a latência e jitter — precisa de QoS (Quality of Service) priorizado. Misturar com dados gerais causa degradação de chamadas. VLANs separadas permitem aplicar políticas de QoS e segurança distintas por tipo de tráfego." },
        ]
      },
    ]
  },
  {
    id: "seguranca",
    name: "Segurança e Auditoria de Sistemas",
    icon: "-",
    chapters: [
      {
        id: "seg-1",
        name: "Cap 1 — Introdução à Segurança",
        cards: [
          { q: "Um ransomware criptografa os arquivos de uma empresa e exige pagamento. Quais pilares da CIA são violados? Cuidado: não é só um.", a: "Disponibilidade (arquivos inacessíveis) E Confidencialidade (atacante pode ter exfiltrado dados antes de criptografar — common em ransomware moderno/double extortion). Integridade também é violada (dados foram alterados/criptografados)." },
          { q: "Um funcionário descontente copia dados de clientes para um pendrive pessoal. Isso é uma ameaça ou vulnerabilidade? Qual pilar da CIA foi violado?", a: "O funcionário é a AMEAÇA (insider threat). A vulnerabilidade é a falta de controle de dispositivos USB / DLP. O pilar violado é Confidencialidade (dados acessados por pessoa não autorizada)." },
          { q: "Uma empresa tem ISO 27001 certificada mas não segue ISO 27002. Isso é possível? Qual a consequência prática?", a: "É possível mas incoerente — ISO 27001 EXIGE implementar controles de segurança, e a 27002 é o guia de boas práticas para esses controles. Na prática, seria difícil manter a certificação 27001 sem seguir as recomendações da 27002 (o auditor questionaria)." },
          { q: "A LGPD exige 'base legal' para tratar dados pessoais. Um site coleta CPF sem consentimento para 'interesse legítimo'. Quando isso é válido?", a: "Interesse legítimo é válido quando: o tratamento é necessário para um interesse real do controlador, não há conflito com direitos do titular, e a expectativa do titular é razoável. Coletar CPF sem justificativa clara dificilmente se enquadra — o consentimento seria a base mais adequada." },
          { q: "Risco = Probabilidade × Impacto. Se uma vulnerabilidade tem probabilidade alta de exploração mas impacto baixo, ela deve ser priorizada sobre outra com probabilidade baixa mas impacto crítico?", a: "Depende do apetite ao risco, mas geralmente a de IMPACTO CRÍTICO tem prioridade — um único evento catastrófico (ex: breach de dados de clientes) pode ser mais danoso que muitos eventos menores. Matrizes de risco colocam impacto como eixo mais pesado." },
          { q: "Um SGSI baseado na ISO 27001 segue o ciclo PDCA. Se a empresa implementa controles (Do) mas nunca faz auditorias internas (Check), o que acontece?", a: "O SGSI perde eficácia — controles podem se degradar, novas vulnerabilidades não são detectadas, e não-conformidades se acumulam. Sem Check, não há melhoria contínua (Act). Na prática, a certificação seria revogada na auditoria de recertificação." },
          { q: "Uma política de segurança define senhas de no mínimo 12 caracteres. A equipe de TI configura o AD para exigir 8. Onde está a falha?", a: "Gap entre política e implementação técnica — a política existe mas o controle técnico não a aplica. Em auditoria, isso é um finding de não-conformidade. A política é inútil se não for enforced por controles técnicos e verificada por monitoramento." },
          { q: "Phishing é classificado como ameaça ou vulnerabilidade? E a falta de treinamento de conscientização dos funcionários?", a: "Phishing = ameaça (o ataque em si). Falta de treinamento = vulnerabilidade (fraqueza que permite a ameaça ter sucesso). A relação: ameaças exploram vulnerabilidades. Treinar funcionários reduz a vulnerabilidade, não elimina a ameaça." },
        ]
      },
      {
        id: "seg-2",
        name: "Cap 2 — Controle de Acesso",
        cards: [
          { q: "Um usuário faz login com senha e recebe um código SMS. Isso é MFA? E se fosse senha + pergunta secreta?", a: "Senha + SMS = SIM, é MFA (algo que sabe + algo que tem). Senha + pergunta secreta = NÃO é MFA, são dois fatores do MESMO tipo (algo que sabe + algo que sabe). MFA exige fatores de categorias DIFERENTES." },
          { q: "Num hospital, enfermeiros do turno noturno não devem acessar prontuários fora do horário. RBAC ou ABAC resolve melhor? Por quê?", a: "ABAC — permite regras baseadas em atributos contextuais (horário, localização, turno). RBAC só controla por papel (enfermeiro = acesso a prontuários, sem restrição de horário). ABAC: 'SE papel=enfermeiro E horário=noturno E turno=atual ENTÃO permitir'." },
          { q: "OAuth 2.0 é um protocolo de autorização, não de autenticação. Qual a diferença prática? Quando usar OpenID Connect em vez de OAuth?", a: "OAuth 2.0: 'app X pode acessar seus dados no serviço Y' (autorização — permissões). OpenID Connect: 'quem é esse usuário?' (autenticação — identidade). Usar OIDC quando precisa saber QUEM é o usuário. OAuth quando só precisa de PERMISSÃO para acessar um recurso." },
          { q: "Zero Trust diz 'nunca confie, sempre verifique'. Um laptop corporativo dentro da rede interna é automaticamente confiável em Zero Trust?", a: "NÃO — Zero Trust não confia em nenhum dispositivo/usuário por localização. O laptop dentro da rede interna ainda precisa: autenticação, verificação de postura (patches, antimalware atualizado), autorização por recurso, e monitoramento contínuo." },
          { q: "SSO permite um login para múltiplos sistemas. Se a senha SSO for comprometida, qual o impacto comparado a senhas separadas por sistema?", a: "Impacto MUITO maior — uma credencial comprometida dá acesso a TODOS os sistemas integrados ao SSO. É o trade-off: SSO reduz fadiga de senhas (menos phishing/anotações) mas cria ponto único de falha. Por isso SSO deve ter MFA obrigatório." },
          { q: "O princípio do menor privilégio diz que um DBA só deve ter acesso ao banco que administra. Na prática, por que isso é difícil de implementar?", a: "Privilege creep — ao longo do tempo, permissões são adicionadas para tarefas pontuais e nunca removidas. Mudanças de função não revogam acessos antigos. Aplicações legadas exigem admin. Falta de revisão periódica de acessos (access review)." },
          { q: "Biometria de impressão digital é 'algo que você é'. Pode ser comprometida? Se sim, qual a diferença crítica vs comprometer uma senha?", a: "SIM — digitais podem ser clonadas (molde de silicone, foto de alta resolução). Diferença crítica: você pode trocar uma senha, mas NÃO pode trocar sua impressão digital. Uma vez comprometida, é permanentemente insegura para aquele dedo." },
          { q: "Um sistema usa RBAC com os papéis: admin, editor, viewer. Um novo requisito exige que editores só editem documentos do seu departamento. Precisamos migrar para ABAC?", a: "Não necessariamente — pode-se refinar o RBAC com sub-papéis (editor-financeiro, editor-RH) ou usar RBAC + filtros por departamento. Porém, se os requisitos de contexto ficarem complexos (horário + departamento + localização), ABAC é mais escalável e flexível." },
        ]
      },
      {
        id: "seg-3",
        name: "Cap 3 — Segurança em SO",
        cards: [
          { q: "Um servidor Linux tem os serviços Telnet, FTP, CUPS e SSH habilitados. No hardening, quais desabilitar e qual manter? Justifique.", a: "Desabilitar: Telnet (texto puro, usar SSH), FTP (texto puro, usar SFTP/SCP), CUPS (servidor de impressão, desnecessário se não for print server). Manter: SSH (acesso remoto seguro, criptografado). Princípio: desabilitar tudo que não é explicitamente necessário." },
          { q: "Uma CVE crítica foi publicada segunda-feira. A equipe planeja aplicar o patch na janela de manutenção de sábado. Qual o risco dessa espera de 5 dias?", a: "Exploits para CVEs críticas podem aparecer em horas (not days) — atacantes monitoram publicações de CVEs. 5 dias de exposição a uma vulnerabilidade conhecida com exploit público é risco altíssimo. Patches críticos devem ter processo de aplicação emergencial fora da janela regular." },
          { q: "Um container Docker roda como root. Um atacante consegue RCE dentro do container. Qual o risco adicional comparado a um container rootless?", a: "Root no container = root no host se houver escape de container (kernel exploit, volume mounts mal configurados). Container rootless: mesmo com escape, o processo seria um usuário não-privilegiado no host — blast radius muito menor." },
          { q: "Logs de auditoria mostram 500 tentativas de login falhadas no user 'admin' em 3 minutos. Isso é um ataque? Qual tipo e como mitigar?", a: "Sim — brute force ou credential stuffing no user admin. Mitigação: account lockout após N tentativas, rate limiting, MFA, renomear a conta admin padrão, CAPTCHA após falhas, alertas automatizados, IP blocking." },
          { q: "Um antimalware baseado em assinaturas não detecta um malware novo (zero-day). Que tipo de detecção teria mais chance de pegá-lo?", a: "Detecção baseada em comportamento/heurística — analisa ações suspeitas (ex: processo criptografando muitos arquivos, injetando em outros processos, acessando APIs sensíveis) em vez de comparar com assinaturas conhecidas. EDR com machine learning também ajuda." },
          { q: "VM escape: um atacante sai de uma VM e compromete o hypervisor. Qual o impacto em outras VMs no mesmo host? Por que isso é pior que comprometer um container?", a: "TODAS as VMs no host ficam comprometidas — o hypervisor tem acesso total à memória e disco de todas as VMs. Pior que container porque: VMs têm isolamento mais forte que containers (kernel próprio), então um escape de VM indica exploit mais grave e o blast radius é maior." },
          { q: "Um firewall host-based bloqueia conexões de entrada na porta 445 (SMB). Isso impede WannaCry? E se o malware vier por e-mail?", a: "Bloquear porta 445 impede propagação lateral via SMB (como WannaCry se espalhava). MAS se o malware chegar via e-mail (phishing), o firewall de porta é inútil — o malware executa localmente e criptografa sem usar rede. Defesa em profundidade: firewall + antimalware + e-mail filtering + patching (MS17-010)." },
          { q: "CIS Benchmarks recomendam desabilitar autorun no Windows. Que vetor de ataque isso previne?", a: "Ataques via mídia removível (USB) — malware em pendrives que executa automaticamente quando inserido (ex: Stuxnet usou autorun em USBs para infectar sistemas air-gapped). Sem autorun, o usuário precisa executar manualmente, adicionando uma camada de decisão." },
        ]
      },
      {
        id: "seg-4",
        name: "Cap 4 — Criptografia",
        cards: [
          { q: "AES-256 é simétrico e RSA-2048 é assimétrico. Por que HTTPS usa os DOIS juntos em vez de só um?", a: "RSA é ~1000x mais lento que AES — inviável para criptografar dados em massa. HTTPS usa RSA/ECDH apenas para trocar uma chave simétrica (key exchange), depois usa AES para criptografar o tráfego. Combinação: segurança da assimétrica + performance da simétrica." },
          { q: "MD5 gera hashes de 128 bits. SHA-256 gera de 256 bits. Ambos são 'funções hash'. Por que MD5 é considerado inseguro?", a: "MD5 tem colisões práticas conhecidas — é possível criar dois arquivos diferentes com o mesmo hash MD5 (ataque de colisão). SHA-256 não tem colisões práticas. Para integridade verificável (assinaturas, certificados), MD5 é inseguro. Para checksums simples (verificar download corrompido) ainda funciona." },
          { q: "TLS 1.3 removeu RSA key exchange. Por que isso é uma melhoria de segurança e não uma perda?", a: "RSA key exchange não tem forward secrecy — se a chave privada do servidor for comprometida no futuro, todo o tráfego passado pode ser decifrado. TLS 1.3 força Diffie-Hellman ephemeral (DHE/ECDHE) que gera chaves por sessão. Comprometer a chave privada não decifra tráfego antigo." },
          { q: "Uma assinatura digital usa a chave PRIVADA do remetente. Se alguém verificar com a chave PÚBLICA e for válida, o que isso prova?", a: "Prova 3 coisas: Autenticidade (só o dono da chave privada poderia ter assinado), Integridade (o documento não foi alterado após a assinatura), Não-repúdio (o remetente não pode negar que assinou). NÃO prova confidencialidade — assinatura não criptografa o conteúdo." },
          { q: "Um certificado X.509 expirou mas o site ainda funciona. O navegador mostra aviso. O que acontece se o usuário ignorar o aviso?", a: "A conexão TLS ainda é criptografada, MAS a identidade do servidor não é verificável — pode ser um ataque man-in-the-middle com certificado expirado. Sem validação do certificado, não há garantia de que o site é quem diz ser. Nunca ignorar em sites com dados sensíveis." },
          { q: "Diffie-Hellman permite trocar chaves sem canal seguro prévio. Por que ele é vulnerável a man-in-the-middle se usado sozinho?", a: "DH não autentica as partes — um atacante pode se posicionar entre A e B, fazer DH separado com cada um (A↔Atacante e Atacante↔B) e interceptar/modificar tudo. Solução: combinar DH com autenticação (certificados/assinaturas) — é o que TLS faz." },
          { q: "Computadores quânticos quebrarão RSA e ECC. O NIST padronizou CRYSTALS-Kyber como substituto. Qual o tipo de problema matemático que o protege?", a: "Lattice-based cryptography (criptografia baseada em reticulados) — especificamente o problema Module Learning With Errors (MLWE). Diferente de RSA (fatoração de primos) e ECC (logaritmo discreto em curvas), problemas de reticulado não têm algoritmo quântico eficiente conhecido." },
          { q: "3DES aplica DES três vezes: Encrypt-Decrypt-Encrypt (EDE). Se as 3 chaves forem iguais, o resultado é equivalente a quê?", a: "DES simples — E(K)→D(K)→E(K) com mesma chave resulta em uma única cifragem DES (o Decrypt desfaz o primeiro Encrypt, sobrando um Encrypt). É por design: 3DES com chaves iguais é retrocompatível com DES. Segurança real exige 2 ou 3 chaves diferentes." },
          { q: "LGPD exige que dados pessoais sejam protegidos. Criptografar dados em repouso (at rest) é suficiente?", a: "Não — é necessário proteger dados em repouso (AES no disco), em trânsito (TLS na rede) e em uso (técnicas como enclaves seguros). Além disso, LGPD exige controle de acesso, consentimento, logs, anonimização quando possível e direito ao esquecimento." },
        ]
      },
      {
        id: "seg-5",
        name: "Cap 5 — Segurança de Redes e DevSecOps",
        cards: [
          { q: "Um IDS detecta um ataque mas não bloqueia. Um IPS bloqueia automaticamente. Qual o risco de um IPS com muitos falsos positivos?", a: "Bloqueia tráfego legítimo — DoS autoinfligido. Usuários não conseguem trabalhar, serviços ficam indisponíveis. Por isso IPS requer tuning cuidadoso. Falsos positivos em IDS são toleráveis (apenas alertas); em IPS são destrutivos (bloqueia de verdade)." },
          { q: "NAC (802.1X) verifica se o dispositivo está em conformidade antes de conectar à rede. Um visitante conecta o notebook pessoal. O que acontece?", a: "O NAC detecta que o dispositivo não está registrado/em conformidade (sem agente corporativo, sem patches, sem antimalware aprovado). Ações típicas: negar acesso, direcionar para rede de quarentena/guest com acesso limitado, ou exigir remediação antes de permitir acesso completo." },
          { q: "Zero Trust Architecture (NIST 800-207) vs segurança de perímetro tradicional: num cenário de trabalho remoto massivo, qual modelo é mais eficaz?", a: "ZTA — no perímetro tradicional, uma vez dentro da VPN o usuário tem acesso amplo à rede interna. Com trabalho remoto massivo, o 'dentro' e 'fora' perdem sentido. ZTA verifica cada acesso individualmente (identidade + postura + contexto), independente da localização." },
          { q: "Uma empresa usa SIEM. O analista recebe 5.000 alertas por dia. Apenas 10 são reais. Isso é um problema de quê e como resolver?", a: "Alert fatigue — excesso de falsos positivos. Soluções: tuning de regras de correlação, machine learning para priorização, SOAR para automação de resposta a alertas repetitivos, threat intelligence para enriquecer e filtrar, e baseline comportamental para reduzir ruído." },
          { q: "SAST encontrou uma vulnerabilidade de SQL Injection no código. DAST não detectou a mesma falha. Por que a discrepância?", a: "SAST analisa código-fonte (vê o código vulnerável mas pode ser falso positivo se houver sanitização em outra camada). DAST testa a aplicação rodando — se um WAF, parametrized query ou input validation bloquear o injection em runtime, DAST não detecta. São complementares, não redundantes." },
          { q: "DevSecOps integra segurança no pipeline CI/CD. Se SAST e DAST rodam DEPOIS do deploy em produção, isso é DevSecOps?", a: "Não — o princípio é 'shift left' (mover segurança para o mais cedo possível). SAST deve rodar no commit/PR (pré-merge). DAST no ambiente de staging (pré-produção). Rodar após deploy em produção é segurança reativa, não DevSecOps." },
          { q: "OWASP Top 10 inclui 'Broken Access Control' como #1. Um IDOR (Insecure Direct Object Reference) permite acessar dados de outros usuários mudando o ID na URL. Qual controle resolve?", a: "Verificação de autorização no servidor — não basta autenticar o usuário, é preciso verificar se ele TEM PERMISSÃO de acessar aquele recurso específico (ex: user.id === resource.owner_id). Nunca confiar em IDs vindos do cliente. Usar UUIDs em vez de IDs sequenciais dificulta mas não resolve — autorização server-side é obrigatória." },
          { q: "SASE combina SD-WAN + CASB + FWaaS + secure web gateway. Por que isso é mais adequado que componentes separados on-premise para organizações cloud-first?", a: "Componentes on-premise criam backhauling (tráfego cloud volta ao data center para segurança, depois sai de novo) — latência e custo. SASE aplica segurança no edge/cloud, perto do usuário e dos dados, sem desviar tráfego. Gestão unificada em vez de N consoles separados." },
          { q: "DNSSEC adiciona assinaturas digitais às respostas DNS. Por que a adoção é baixa se protege contra DNS spoofing/cache poisoning?", a: "Complexidade operacional: gerenciar chaves, rotação de chaves (key rollover), aumento do tamanho das respostas DNS (pode causar fragmentação UDP), risco de interrupção se configuração falhar, e falta de incentivo (muitos acham TLS suficiente para autenticidade do destino)." },
          { q: "Uma empresa sofreu um incidente. Na fase de 'Contenção', a equipe decide desligar o servidor comprometido. Isso pode ser um erro? Por quê?", a: "Sim — desligar destrói evidências voláteis: processos em execução, conexões de rede ativas, memória RAM (malware fileless, chaves de criptografia), cache. O correto é ISOLAR da rede (não desligar), capturar memória e artefatos forenses, depois decidir sobre desligamento." },
        ]
      },
      {
        id: "seg-6",
        name: "Cap 6 — Gestão de Riscos",
        cards: [
          { q: "NIST SP 800-39 define 3 níveis de gestão de riscos. Uma vulnerabilidade no servidor web afeta qual nível? E uma decisão de aceitar risco de não ter backup offsite?", a: "Vulnerabilidade no servidor = Nível 3 (Sistema de Informação). Decisão de aceitar risco de backup = Nível 1 (Organizacional, pois é uma decisão estratégica que afeta toda a empresa). Nível 2 (Processo de Negócio) seria, por ex., risco em um processo de e-commerce." },
          { q: "No RMF do NIST, a etapa 'Authorize' é quando o sistema recebe Authority to Operate (ATO). Um sistema recebeu ATO há 2 anos sem re-avaliação. Qual o risco?", a: "A postura de segurança degradou — novas vulnerabilidades surgiram, configurações podem ter mudado, ameaças evoluíram. A etapa 'Monitor' (contínua) deveria estar atualizando o risco. ATO sem monitoramento contínuo é autorização baseada em estado obsoleto." },
          { q: "O modelo FAIR quantifica risco financeiramente. Qual a vantagem sobre uma matriz qualitativa 5×5 (probabilidade × impacto)?", a: "FAIR gera valores monetários (ex: 'risco anual de $2.3M com ±15%') que gestores de negócio entendem e podem comparar com investimentos em controles. Matrizes 5×5 dizem 'risco alto' — subjetivo, difícil de priorizar entre dois riscos 'altos', e não justifica orçamento específico." },
          { q: "Uma empresa decide TRANSFERIR o risco de ransomware contratando seguro cyber. O risco foi eliminado?", a: "NÃO — transferir risco move o impacto FINANCEIRO, não o risco em si. Se o ransomware atacar: dados ainda ficam indisponíveis, reputação é afetada, operação para, e nem todo custo é coberto pelo seguro (deductibles, exclusões). Transferência deve complementar mitigação, não substituí-la." },
          { q: "MITRE ATT&CK lista técnicas reais de adversários. Como isso é mais útil para threat hunting do que apenas usar CVEs?", a: "CVEs são vulnerabilidades pontuais (falha em um software). ATT&CK mapeia COMPORTAMENTOS — como atacantes se movem lateralmente, persistem, exfiltram. Um threat hunter busca padrões de comportamento (ex: execução via PowerShell + credential dumping + lateral movement) mesmo sem CVE específica." },
          { q: "NIST CSF 2.0 adicionou 'Govern' como função nova. As outras 5 já existiam (Identify, Protect, Detect, Respond, Recover). O que 'Govern' cobre que as outras não cobriam?", a: "Govern: governança, estratégia de risco, políticas, papéis e responsabilidades, integração com objetivos de negócio. Antes, essas atividades ficavam dispersas entre Identify e processos externos. Govern torna a liderança e accountability explícitas no framework." },
          { q: "Uma organização faz pentest (NIST SP 800-115) e encontra que um atacante pode escalar privilégios em 4 passos. Qual a diferença entre corrigir o passo 1 vs o passo 4?", a: "Corrigir passo 1 (ex: acesso inicial) bloqueia toda a cadeia. Corrigir passo 4 (ex: escalação de privilégio) reduz impacto mas o atacante já está dentro. Defesa em profundidade: corrigir TODOS os passos. Mas se forçado a priorizar, o mais cedo na cadeia tem maior impacto preventivo." },
          { q: "BCP e DRP são complementares. Se uma empresa tem DRP mas NÃO tem BCP, o que pode acontecer durante um desastre?", a: "DRP restaura TI (sistemas, dados) — mas sem BCP, a empresa não sabe como manter operações de NEGÓCIO durante o downtime: comunicação com clientes, processos manuais alternativos, cadeia de comando, site alternativo. TI volta mas o negócio pode já ter perdido clientes e receita." },
          { q: "CIS Controls v8.1 é priorizado — controles 1-6 são 'básicos'. Controle #1 é 'Inventário e Controle de Ativos Corporativos'. Por que é o PRIMEIRO?", a: "Impossível proteger o que não se conhece. Sem inventário: shadow IT, dispositivos não patcheados, servidores esquecidos. Todos os outros controles (patches, configuração, monitoramento) dependem de saber O QUE EXISTE. É a fundação de todo o programa de segurança." },
        ]
      },
      {
        id: "seg-7",
        name: "Cap 7 — Auditoria de SI e BD",
        cards: [
          { q: "Uma auditoria interna encontra que o DBA tem permissão de INSERT e DELETE sem segregação de funções. Por que isso é um finding e qual o risco?", a: "Violação de SoD — o DBA pode inserir dados fraudulentos E apagar rastros (logs, registros). Sem segregação, não há controle compensatório. Risco: fraude indetectável. Controle: DBA não deve ter acesso direto a dados de produção sem aprovação, e logs devem ser imutáveis (write-once)." },
          { q: "ISO 19011 lista 'independência' como princípio de auditoria. Um auditor que foi o consultor que implementou o sistema sendo auditado viola esse princípio?", a: "Sim — é a ameaça ética de 'auto-revisão'. O auditor tem viés (tendência a não encontrar falhas na própria implementação) e conflito de interesse. ISO 19011 exige que auditores sejam independentes da área auditada. Outro auditor deve ser designado." },
          { q: "CAATs (Computer-Assisted Audit Techniques) detectam que 300 de 10.000 transações têm valores exatamente em R$9.999 (abaixo do limite de R$10.000 que requer aprovação gerencial). O que isso indica?", a: "Possível structuring/splitting de transações para evitar o controle de aprovação (threshold fraud). Padrão suspeitamente concentrado logo abaixo do limite = red flag. O auditor deve investigar: mesmo fornecedor? mesmo funcionário? datas próximas? Se confirmado, é evidência de fraude." },
          { q: "ITAF da Isaca e ISO 19011 são frameworks de auditoria diferentes. Quando usar cada um?", a: "ITAF: específico para auditoria de TI/SI (sistemas, segurança, dados). ISO 19011: genérico para auditoria de QUALQUER sistema de gestão (qualidade, ambiental, segurança da informação). Para auditoria de banco de dados, ITAF é mais adequado. Para auditoria do SGSI ISO 27001, ISO 19011 orienta o processo." },
          { q: "Uma auditoria de BD revela que backups existem mas nunca foram testados (restore test). O auditor deve classificar como finding ou observação?", a: "Finding (achado significativo) — backup sem teste de restore é potencialmente inútil. Se precisar recuperar e o backup estiver corrompido/incompleto, o impacto é perda de dados. É um controle que EXISTE mas não foi VERIFICADO, então sua eficácia é desconhecida." },
          { q: "Oracle AVDF monitora queries no banco de dados. Um DBA executa 'SELECT * FROM salarios WHERE nome LIKE \"%diretor%\"'. Isso deve gerar alerta? Por quê?", a: "Sim — acesso a dados sensíveis (salários de diretores) por um DBA é anomalia potencial (privilege abuse). AVDF deve ter política de alerta para: tabelas sensíveis, queries com padrões suspeitos (LIKE genérico em tabelas de RH/financeiro), acessos fora do horário. O DBA não precisa ver dados de negócio para administrar o banco." },
          { q: "No follow-up de auditoria, o auditado implementou 8 de 10 recomendações. As 2 restantes foram 'aceitas com risco residual'. Isso é aceitável?", a: "Sim, SE: 1) o risco residual foi formalmente documentado, 2) a gestão (não o auditado sozinho) aceitou o risco, 3) está dentro do apetite ao risco da organização, 4) controles compensatórios foram implementados. 'Aceitar risco' é tratamento válido, desde que consciente e documentado." },
          { q: "Extended Events do SQL Server são mais leves que SQL Profiler/Trace. Por que isso importa para auditoria em produção?", a: "Auditoria com alto overhead (Profiler) degrada performance do banco em produção — pode causar indisponibilidade (viola o pilar de Disponibilidade enquanto tenta garantir segurança). Extended Events usam processamento assíncrono e buffers eficientes, permitindo auditoria contínua sem impacto perceptível." },
        ]
      },
      {
        id: "seg-8",
        name: "Cap 8 — Governança de TI e Ética",
        cards: [
          { q: "COBIT 2019 tem domínios APO, DSS e MEA. Uma empresa monitora seus SLAs de TI mas não alinha TI com estratégia de negócio. Qual domínio está falhando?", a: "APO (Alinhar, Planejar e Organizar) — responsável por garantir que TI suporta os objetivos estratégicos. Monitorar SLAs é MEA (Monitorar, Avaliar e Analisar). A empresa tem controle operacional mas falta governança estratégica — TI funciona mas pode não entregar valor ao negócio." },
          { q: "FIPS 199 classifica impacto como Baixo, Moderado ou Alto. Um sistema de RH com dados de salários é classificado como 'Baixo'. Isso está correto?", a: "Provavelmente NÃO — dados de salários são PII (informações pessoais) com impacto potencialmente alto em Confidencialidade (violação de privacidade, LGPD). Moderado a Alto seria mais adequado. Classificação incorreta resulta em controles insuficientes." },
          { q: "Um auditor descobre irregularidades financeiras durante uma auditoria de TI. Ele deve reportar no relatório de TI ou comunicar separadamente? Qual princípio ético guia a decisão?", a: "Comunicar separadamente e imediatamente ao comitê de auditoria/gestão superior — não esperar o relatório final. Princípio: Integridade e Comportamento Profissional. Se incluir no relatório de TI, pode demorar e a irregularidade pode ser encoberta. Em alguns casos, comunicação a reguladores é obrigatória." },
          { q: "A ameaça ética de 'familiaridade' ocorre quando o auditor tem relacionamento próximo com o auditado. Cite um cenário concreto e como mitigar.", a: "Cenário: auditor almoça frequentemente com o gerente de TI sendo auditado — pode não reportar falhas por constrangimento pessoal. Mitigação: rodízio de auditores, declaração de conflito de interesse, supervisão do trabalho por outro auditor sênior, códigos de conduta que limitam interações sociais com auditados." },
          { q: "NISTIR 8286 integra CSRM (Cybersecurity Risk Management) com ERM (Enterprise Risk Management). Se estão separados, qual o problema prático?", a: "Gestores de negócio não entendem riscos cyber isolados ('SQLi na API de pagamento') e não priorizam investimento. Integração traduz: 'risco de perda de R$5M/ano por breach de dados de cartão' — linguagem de negócio que justifica orçamento. Sem integração, cyber compete por orçamento sem argumentos financeiros." },
          { q: "Um relatório de auditoria usa jargão técnico pesado para a diretoria. O resultado: nenhuma recomendação é implementada. Onde está o erro?", a: "Falha de comunicação — o relatório deve ter duas versões: sumário executivo em linguagem de negócio (impacto financeiro, risco para o negócio, ações prioritárias) e anexo técnico com detalhes. Se a diretoria não entende, não prioriza. A comunicação eficaz é responsabilidade do auditor, não do leitor." },
          { q: "Uma auditoria resulta em opinião 'satisfatória baixa'. O auditado argumenta que deveria ser 'satisfatória alta' porque 80% dos controles estão em conformidade. Quem tem razão?", a: "Depende da MATERIALIDADE dos 20% não-conformes. Se os controles falhos incluem autenticação, backup de dados críticos ou segregação de funções, 80% de conformidade em controles menores não compensa. A opinião global pondera severidade, não apenas quantidade." },
          { q: "ABNT NBR ISO/IEC 38500 define 6 princípios de governança de TI. 'Comportamento humano' é um deles. Por que incluir um princípio 'humano' em governança de TI?", a: "Porque tecnologia é usada por PESSOAS — ignorar fatores humanos (resistência a mudanças, usabilidade, ética, treinamento) leva a falhas de adoção e segurança. Políticas perfeitas falham se usuários as contornam. Governança deve considerar cultura organizacional, capacitação e bem-estar dos usuários." },
        ]
      },
    ]
  }
];

export default STUDY_COURSES;
